/* ============================================================
   sessions.js — 수정 가능한 세션 데이터
   이미지, 타이틀, 설명, URL 등을 여기서 관리하세요.
   ============================================================

   각 세션 항목 필드:
   - id        : 고유 ID (폴더명, URL 슬러그로 사용)
   - title     : 세션 제목
   - mentor    : 멘토 이름
   - emoji     : 퍼즐 조각에 표시할 이모지
   - color     : 조각 배경색 (hex)
   - textColor : 조각 텍스트 색 ('#000' 또는 '#fff')
   - description : 툴팁에 표시할 설명
   - note      : (선택) 추가 메모 — 툴팁 설명 뒤에 붙음
   - url       : 세션 링크 (준비 전엔 '#' 유지)
   - status    : 'active' | 'coming-soon' | 'future'
   - image     : (선택) 이미지 경로 — 나중에 추가 가능
                  예: 'assets/images/sessions/debugging/cover.png'
   ============================================================ */

const SESSIONS = [
  {
    id: 'debugging',
    title: 'Debugging',
    mentor: 'Howard',
    emoji: '🐛',
    color: '#FFE600',
    textColor: '#000',
    description: 'iOS 앱 디버깅의 핵심을 파고듭니다. 중단점 활용, LLDB, Xcode 진단 도구를 체계적으로 학습합니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/debugging/cover.png',
  },
  {
    id: 'healthcare',
    title: 'HealthCare',
    mentor: 'Lingo',
    emoji: '🏥',
    color: '#FF4D6A',
    textColor: '#fff',
    description: 'HealthKit, CareKit 등 Apple 헬스 데이터 API를 활용해 건강 중심의 앱을 만들어봅니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/healthcare/cover.png',
  },
  {
    id: 'testing-lab',
    title: 'Testing Lab',
    mentor: 'Jaesung',
    emoji: '🧪',
    color: '#00D26A',
    textColor: '#000',
    description: 'Swift 및 SwiftUI 앱을 위한 유닛 테스트, UI 테스트, 테스트 주도 개발(TDD) 방법론을 실습합니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/testing-lab/cover.png',
  },
  {
    id: 'concurrency-lab',
    title: 'Concurrency Lab',
    mentor: 'Jaesung',
    emoji: '⚡',
    color: '#0047FF',
    textColor: '#fff',
    description: 'Swift Concurrency 심화 탐구: async/await, Actor, 구조화된 동시성과 성능 최적화를 다룹니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/concurrency-lab/cover.png',
  },
  {
    id: 'package-lab',
    title: 'Package Lab',
    mentor: 'Jaesung',
    emoji: '📦',
    color: '#A0A0A0',
    textColor: '#fff',
    description: 'Swift Package Manager를 활용한 패키지 생성, 배포, 관리 전략을 배웁니다.',
    note: '오픈 준비중',
    ticker: ['📅 시작일 미정', '⏱ 기간 미정', '🚧 준비중'],
    url: '#',
    status: 'coming-soon',
    // image: 'assets/images/sessions/package-lab/cover.png',
  },
  {
    id: 'spatial-computing',
    title: 'Spatial Computing',
    mentor: 'Judy',
    emoji: '🥽',
    color: '#7B2FFF',
    textColor: '#fff',
    description: 'visionOS와 공간 경험의 세계로 뛰어듭니다. Apple Vision Pro를 위한 몰입형 앱을 직접 만들어봅니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/spatial-computing/cover.png',
  },
  {
    id: 'ai-app',
    title: 'AI와 함께 앱 만들기',
    mentor: 'Isaac',
    emoji: '🤖',
    color: '#FF7A00',
    textColor: '#fff',
    description: '온디바이스 AI, CoreML, 최신 AI API를 활용해 지능형 앱을 설계하고 구현합니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/ai-app/cover.png',
  },
  {
    id: 'local-database',
    title: 'Local Database',
    mentor: 'Jason',
    emoji: '🗄️',
    color: '#00BCD4',
    textColor: '#000',
    description: 'SwiftData, Core Data, SQLite를 활용한 로컬 영구 저장소 구현과 데이터 모델링 베스트 프랙티스를 학습합니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/local-database/cover.png',
  },
  {
    id: 'createml',
    title: 'CreateML',
    mentor: 'Jason',
    emoji: '🧠',
    color: '#FF3D71',
    textColor: '#fff',
    description: 'Create ML로 나만의 머신러닝 모델을 학습시킵니다. 4개월 동안 12개의 템플릿을 직접 구현합니다.',
    note: '12 templates · 4 months',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/createml/cover.png',
  },
  {
    id: 'aiml',
    title: 'AIML심화',
    mentor: 'Jason',
    emoji: '⚙️',
    color: '#FFB800',
    textColor: '#000',
    description: 'Metal 성능 최적화, 모델 변환 및 양자화, Foundation Model까지 AI/ML 심화 과정을 탐구합니다.',
    note: 'Metal · Quantization · Foundation Model',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/aiml/cover.png',
  },
  {
    id: 'networking',
    title: 'Networking',
    mentor: 'Nathan',
    emoji: '🌐',
    color: '#1565C0',
    textColor: '#fff',
    description: 'URLSession, 비동기 네트워킹, REST API, WebSocket, 네트워크 진단까지 실전 네트워크 프로그래밍을 익힙니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/networking/cover.png',
  },
  {
    id: 'animation-swiftui',
    title: 'Animation with SwiftUI',
    mentor: 'Leeo',
    emoji: '✨',
    color: '#E91E8C',
    textColor: '#fff',
    description: 'SwiftUI 애니메이션 시스템을 활용해 부드러운 전환 효과와 인터랙티브 모션 디자인을 구현합니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/animation-swiftui/cover.png',
  },
  {
    id: 'computational-thinking',
    title: 'Computational Thinking',
    mentor: 'Leeo',
    emoji: '🧩',
    color: '#76FF03',
    textColor: '#000',
    description: '문제 분해, 알고리즘 설계, 논리적 사고를 통해 더 나은 소프트웨어를 만드는 컴퓨팅 사고력을 키웁니다.',
    url: '#',
    status: 'active',
    // image: 'assets/images/sessions/computational-thinking/cover.png',
  },
];
