/* ============================================================
   sessions.js — 수정 가능한 세션 데이터
   이미지, 타이틀, 설명, URL 등을 여기서 관리하세요.
   ============================================================

   각 세션 항목 필드:
   - id        : 고유 ID (폴더명, URL 슬러그로 사용)
   - title     : 세션 제목
   - mentor    : 멘토 이름
   - emoji     : 퍼즐 조각에 표시할 이모지
   - color     : 조각 배경색 (hex)
   - textColor : 조각 텍스트 색 ('#000' 또는 '#fff')
   - description : 툴팁에 표시할 설명
   - note      : (선택) 추가 메모 — 툴팁 설명 뒤에 붙음
   - ticker    : (선택) 하단 티커 항목 배열 — 날짜, 기간 등 추가 정보
   - url       : 세션 링크 (준비 전엔 '#' 유지)
   - status    : 'active' | 'coming-soon' | 'future'
   - image     : (선택) 이미지 경로 — 나중에 추가 가능
                  예: 'assets/images/sessions/debugging/cover.png'
   ============================================================ */

const SESSIONS = [
  {
    id: 'debugging',
    title: 'Debugging',
    mentor: 'Howard',
    emoji: '🐛',
    color: '#FFE600',
    textColor: '#000',
    description: '하워드가 개발하면서 사용했던 디버깅 스킬들을 공유합니다.',
    ticker: ['📅 C3 기간 중 오프라인', '⏱ 추후 예정', '🔧 디버깅'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1121878194',
    status: 'active',
    // image: 'assets/images/sessions/debugging/cover.png',
  },
  {
    id: 'healthcare',
    title: 'HealthCare',
    mentor: 'Lingo',
    emoji: '🩺',
    color: '#FF4D6A',
    textColor: '#fff',
    description: 'HealthKit, CareKit 등 Apple 헬스 데이터 API를 활용해 건강 중심의 앱을 만들어봅니다.',
    ticker: ['📅 추후 예정', '⏱ 추후 예정', '❤️ HealthKit · CareKit · ResearchKit'],
    url: 'https://da-pos.atlassian.net/wiki/pages/resumedraft.action?draftId=1129283596&draftShareId=ea8675b0-e9e6-4276-bc5b-ec0a642714d0',
    status: 'active',
    // image: 'assets/images/sessions/healthcare/cover.png',
  },
  {
    id: 'testing-lab',
    title: 'Testing Lab',
    mentor: 'Jaesung',
    emoji: '🧪',
    color: '#00D26A',
    textColor: '#000',
    description: '자네, 나의 테스팅 연구실에 들어오겠는가?',
    ticker: ['📅 5월 6일 연구실 지원 오픈', '⏱ C3 중 2주간', '🧪 Swift Testing · XCTest · Test Automation · Test Design'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1132560498/Testing+Lab?atlOrigin=eyJpIjoiM2Q4ZDQwNDgzMzVlNGZkYjhjNTRjMzQ5OGE4Yjk0N2MiLCJwIjoiYyJ9',
    status: 'active',
    // image: 'assets/images/sessions/testing-lab/cover.png',
  },
  {
    id: 'concurrency-lab',
    title: 'Concurrency Lab',
    mentor: 'Jaesung',
    emoji: '🔬',
    color: '#0047FF',
    textColor: '#fff',
    description: '자네, 나의 동시성 연구실에 들어오겠는가?',
    ticker: ['📅 5월 6일 연구실 지원 오픈', '⏱ C3 중 2주간', '🔬 Swift Concurrency · Grand Central Dispatch'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1131774034/Concurrency+Lab?atlOrigin=eyJpIjoiYzU5YTE1ZGRlNTQ4NDM1Y2JjMzY4NDJlMTM5M2M3NWQiLCJwIjoiYyJ9',
    status: 'active',
    // image: 'assets/images/sessions/concurrency-lab/cover.png',
  },
  {
    id: 'package-lab',
    title: 'Package Lab',
    mentor: 'Jaesung',
    emoji: '📦',
    color: '#FF5722',
    textColor: '#fff',
    description: 'Swift Package Manager를 활용한 패키지 생성, 배포, 관리 전략을 배웁니다.',
    note: '오픈 준비중',
    ticker: ['📅 추후 예정', '⏱ 추후 예정', '🚧 준비중'],
    url: 'https://da-pos.atlassian.net/wiki/x/EgCWR',
    status: 'coming-soon',
    // image: 'assets/images/sessions/package-lab/cover.png',
  },
  {
    id: 'spatial-computing',
    title: 'Spatial Computing',
    mentor: 'Judy',
    emoji: '🥽',
    color: '#7B2FFF',
    textColor: '#fff',
    description: 'Spatial Computing의 세계를 함께 탐구하고 본인만의 작품을 만들어 전시를 개최합니다.',
    note: '10월 전시회 예정',
    ticker: ['📅 C3 이후', '⏱ ~10월 (전시회)', '🥽 Spatial Computing · AR · visionOS'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1136526804',
    status: 'active',
    // image: 'assets/images/sessions/spatial-computing/cover.png',
  },
  {
    id: 'ai-app',
    title: 'AI와 함께 앱 만들기',
    mentor: 'Isaac',
    emoji: '🤖',
    color: '#FF7A00',
    textColor: '#fff',
    description: 'AI와 함께 간단한 앱을 만들고 앱스토어까지 올려보는 모임.',
    note: '선착순 7명 · Hi-fi까지 3주 후 자율 운영',
    ticker: ['📅 C3 이후 (별도 공지)', '⏱ Hi-fi까지 3주', '🤖 AI 엔지니어링 · 1인 앱개발'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1137377499',
    status: 'active',
    // image: 'assets/images/sessions/ai-app/cover.png',
  },
  {
    id: 'local-database',
    title: 'Local Database',
    mentor: 'Jason',
    emoji: '🗄️',
    color: '#00BCD4',
    textColor: '#000',
    description: 'SwiftData, GRDB, UserDefaults, CloudKit 중 본인에게 필요한 1~2개를 골라 깊게 파봅니다. 페어와 함께 공부하고 결과물은 GitHub에 올려 서로 리뷰합니다. 검사도 사이클도 평가도 없습니다! 내가 이해한 흔적이 남는 게 중요한 테크맵.',
    ticker: ['📅 C3 초중반', '⏱ 3주', '🗄️ SwiftData · GRDB · UserDefaults · CloudKit'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1137575527',
    status: 'active',
    // image: 'assets/images/sessions/local-database/cover.png',
  },
  {
    id: 'createml',
    title: 'CreateML',
    mentor: 'Jason',
    emoji: '🧠',
    color: '#FF3D71',
    textColor: '#fff',
    description: '매주 하나의 CreateML 템플릿을 쌓아가는 4개월짜리 작업실. Jason이 템플릿을 데모로 보여주면, 러너는 다음 주까지 본인 데이터와 아이디어로 모델을 학습시키고 바이브코딩으로 MVP 앱까지 만들어옵니다. 본인에게 필요한 템플릿만 골라 참여해도 됩니다. 연말 전시회에서 누적 결과물을 공개합니다.',
    note: '12 templates · 4개월 · 연말 전시회',
    ticker: ['📅 C3 중반 (첫 테크맵 종료 직후)', '⏱ 4개월 (주 1회)', '🧠 CreateML 12 Templates · 바이브코딩 · MVP'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1136952737',
    status: 'active',
    // image: 'assets/images/sessions/createml/cover.png',
  },
  {
    id: 'aiml',
    title: 'AIML심화',
    mentor: 'Jason',
    emoji: '⚙️',
    color: '#FFB800',
    textColor: '#000',
    description: '3주간 on-device AI 난제 3개를 차례로 맛보는 워크숍. 수학과 이론 깊이는 빼고 "언제, 어떻게, 왜 필요한가"만 다룹니다. 각 주제마다 동작하는 스타터 레포 제공. 세션은 개념 30%, 핸즈온 70%. 목표는 "이해"가 아니라 "접촉과 적용 가능성 판단"입니다. 3주 중 필요한 주차만 골라 참여해도 됩니다.',
    note: '주제별 1주씩 · Not for all',
    ticker: ['📅 C4 이후 시작', '⏱ 3주 (주제별 1주)', '⚙️ Metal · Model Conversion & Quantization · Foundation Model'],
    url: 'https://da-pos.atlassian.net/wiki/x/lgbYQw',
    status: 'active',
    // image: 'assets/images/sessions/aiml/cover.png',
  },
  {
    id: 'networking',
    title: 'Networking',
    mentor: 'Nathan',
    emoji: '🌐',
    color: '#1565C0',
    textColor: '#fff',
    description: '우리가 흔히 부르는 API(REST API)에 대한 이해와 Swift를 활용한 호출/응답 구현을 배우고 경험합니다.',
    ticker: ['📅 5월 18일 시작', '⏱ 3주', '🌐 REST API · Postman · URLSession · Alamofire'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/PA26/pages/1140622188/Networking',
    status: 'active',
    // image: 'assets/images/sessions/networking/cover.png',
  },
  {
    id: 'animation-swiftui',
    title: 'Animation with SwiftUI',
    mentor: 'Leeo',
    emoji: '✨',
    color: '#E91E8C',
    textColor: '#fff',
    description: 'SwiftUI 애니메이션 시스템을 활용해 부드러운 전환 효과와 인터랙티브 모션 디자인을 구현합니다.',
    ticker: ['📅 추후 예정', '⏱ 추후 예정', '✨ Animation · Transition · Motion'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/Mentors/pages/1104773148/Tech+Map+Animation+with+SwiftUI?themeState=dark%3Adark+light%3Alight+spacing%3Aspacing+typography%3Atypography+colorMode%3Alight',
    status: 'active',
    // image: 'assets/images/sessions/animation-swiftui/cover.png',
  },
  {
    id: 'computational-thinking',
    title: 'Computational Thinking',
    mentor: 'Leeo',
    emoji: '🧩',
    color: '#76FF03',
    textColor: '#000',
    description: '문제 분해, 알고리즘 설계, 논리적 사고를 통해 더 나은 소프트웨어를 만드는 컴퓨팅 사고력을 키웁니다.',
    ticker: ['📅 추후 예정', '⏱ 추후 예정', '🧩 Algorithm · Logic · Problem Solving'],
    url: 'https://da-pos.atlassian.net/wiki/spaces/Mentors/pages/1103298601/Tech+Map+Computational+Thinking',
    status: 'active',
    // image: 'assets/images/sessions/computational-thinking/cover.png',
  },
];
